# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
# @2026.01.11 nice_nano_v2 is renamed to nice_nano, see: https://www.answeroverflow.com/m/1449500711137050645
---
include:
  - board: nice_nano
    shield: corne_left
  - board: nice_nano
    shield: corne_right
